name: Simple Qt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'

    - name: Install build tools and X virtual framebuffer
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential xvfb

    - name: Create compatibility header for QMessageBox.h
      run: echo '#include <QMessageBox>' > QMessageBox.h

    - name: Build project
      run: |
        qmake "TIC_TAC_TOE_FINAL - game.pro"
        make

    - name: Run program with GUI support
      run: |
        EXECUTABLE="TIC_TAC_TOE_FINAL - game"
        if [[ -f "$EXECUTABLE" ]]; then
          xvfb-run -a ./$EXECUTABLE
        else
          echo "Executable not found!"
          exit 1
        fi

  run-cpplint:
    name: Run cpplint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install cpplint
      run: pip install cpplint

    - name: Run cpplint on all .cpp and .h files
      run: |
        find . -name "*.cpp" -o -name "*.h" | xargs cpplint || true
