name: Simple Qt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'

    - name: Install build tools and X virtual framebuffer
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential xvfb

    - name: Build project
      run: |
        qmake
        make

    - name: Run program with GUI support
      run: |
        EXECUTABLE=your_app_name  # ← غيره لو اسمك غير كده
        if [[ -f "$EXECUTABLE" ]]; then
          xvfb-run -a ./"$EXECUTABLE"
        else
          echo "Executable not found!"
          exit 1
        fi
