name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev build-essential

    - name: Build project
      run: |
        qmake TIC_TAC_TOE_FINAL - game.pro
        make

    - name: Run tests
      run: |
        if [ -f test.sh ]; then
          chmod +x test.sh
          ./test.sh
        else
          echo "No test script found."
        fi

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: tic-tac-toe-build
        path: |
          ./debug/
          ./release/

