name: Simple Qt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'

    - name: Build project
      run: |
        qmake "TIC_TAC_TOE_FINAL - game.pro"
        make

    - name: List all executables after build
      run: find . -type f -executable

  run-cpplint:
    name: Run cpplint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install cpplint
      run: pip install cpplint

    - name: Run cpplint on all .cpp and .h files
      run: |
        find . -name "*.cpp" -o -name "*.h" | xargs cpplint || true

  performance-test:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    needs: build-and-run

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'

    - name: Install performance monitoring tools
      run: |
        sudo apt-get update
        sudo apt-get install -y time valgrind

    - name: Build performance test
      run: |
        qmake test_components.pro
        make

    - name: Run performance tests with time measurement
      run: |
        echo "Running performance tests with time measurement..."
        /usr/bin/time -v ./test_components 2> time_results.txt
        cat time_results.txt

    - name: Run performance tests with Valgrind
      run: |
        echo "Running performance tests with Valgrind..."
        valgrind --tool=callgrind --callgrind-out-file=callgrind.out ./test_components
        valgrind --tool=massif --massif-out-file=massif.out ./test_components

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: |
          time_results.txt
          callgrind.out
          massif.out
